// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uelgkuzcneqaowcmpqde.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlbGdrdXpjbmVxYW93Y21wcWRlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0OTIzMjMsImV4cCI6MjA3MjA2ODMyM30.6sabuvn2nNmwuw13KvKuivCWJVrcLDPKFCTI2uFistw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});